name: Create Release

on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: false
        description: 'Version without v prefix'
  push:
    branches: [ main ]
    paths:
    - '.oss-config.json'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true

    - name: Tag
      id: tag
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.version }}" != "" ]]; then
          echo "::set-output name=tag::${{ github.event.inputs.version }}"
          exit 0
        fi
        echo "::set-output name=tag::some-processed-value"

    - name: Print
      run: |
        echo "v${{ steps.tag.outputs.tag }}"
